name: app_image_search_toy
description: "Search Image & Favorite"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  dio: 5.7.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  logger: 2.4.0
  photo_view: 0.15.0
  fluttertoast: 8.2.8
  cached_network_image: ^3.4.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: 2.0.1
  build_runner: 2.4.11

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true